sources:
  - glyphs/Onest-Black.ufo
  - glyphs/Onest-Bold.ufo
  - glyphs/Onest-ExtraBold.ufo
  - glyphs/Onest-Light.ufo
  - glyphs/Onest-Medium.ufo
  - glyphs/Onest-Regular.ufo
  - glyphs/Onest-Thin.ufo
axisOrder:
  - wght
familyName: Onest
outputDir: "../fonts"
