sources:
  - glyphs/Onest-Black.ufoz
  - glyphs/Onest-Bold.ufoz
  - glyphs/Onest-ExtraBold.ufoz
  - glyphs/Onest-Light.ufoz
  - glyphs/Onest-Medium.ufoz
  - glyphs/Onest-Regular.ufoz
  - glyphs/Onest-Thin.ufoz
axisOrder:
  - wght
familyName: Onest
outputDir: "../fonts"
