sources:
  - Onest-Black.glyphs
  - Onest-Bold.glyphs
  - Onest-ExtraBold.glyphs
  - Onest-Light.glyphs
  - Onest-Medium.glyphs
  - Onest-Regular.glyphs
  - Onest-Thin.glyphs
axisOrder:
  - wght
familyName: Onest
outputDir: "../fonts"
