sources:
  - sources/Onest-Black.glyphs
  - sources/Onest-Bold.glyphs
  - sources/Onest-ExtraBold.glyphs
  - sources/Onest-Light.glyphs
  - sources/Onest-Medium.glyphs
  - sources/Onest-Regular.glyphs
  - sources/Onest-Thin.glyphs
axisOrder:
  - wght
familyName: Onest
outputDir: "../fonts"
